apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: app-guestbook
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: guestbook
  clusterSelector:
    matchExpressions:
      - key: nova.elotl.co/cluster.version
        operator: In
        values:
        - "1.21"
        - "1.25"
      - key: cluster-under-maintenance
        operator: DoesNotExist
  resourceSelectors:
    labelSelectors:
      - matchLabels:
          app.kubernetes.io/instance: guestbook
  groupBy:
    labelKey: app.kubernetes.io/version
  spreadConstraints:
    topologyKey: nova.elotl.co/cluster.version
    percentageSplit:
    - topologyValue: "1.25"
      percentage: 25
    - topologyValue: "1.21"
      percentage: 75
