apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: test-guestbook
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: guestbook-test
  clusterSelector:
    matchExpressions:
      - key: nova.elotl.co/cluster.version
        operator: In
        values:
        - "1.25"
      - key: cluster-under-maintenance
        operator: DoesNotExist
  resourceSelectors:
    labelSelectors:
      - matchLabels:
          app.kubernetes.io/instance: guestbook-test
  groupBy:
    labelKey: app.kubernetes.io/version
